<?php

namespace Arii\JOCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobStatusRepository extends EntityRepository
{
}
