<?php

namespace Arii\JOCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Scheduler_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerHistoryRepository extends EntityRepository
{
}
