<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends EntityRepository
{

    public function listAlarms() {
        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.name,e.stateTime')
        ->getQuery();

        return $q->getResult();
    }

    
}
