<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{
    public function listState($state) {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.status,e.state,e.end_time,e.event_type')
        ->where('e.state = :state')
        ->orderBy('e.end_time','DESC')
        ->setParameter('state',$state)
        ->getQuery();
        return $q->getResult();
    }

    public function Alerts() {
        
        $q = $this
        ->createQueryBuilder('e')
        ->where('e.active = :active')
        ->OrderBy('e.pattern,e.status,e.exit_codes')
        ->setParameter('active', 1)
        ->getQuery();

        return $q->getResult();
    }

    
}
