<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetworkRepository extends EntityRepository
{
    
    public function listNotOK() {
        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.name,e.status,e.last_state_change')
        ->where('e.status != :status')
        ->orderBy('e.name')
        ->setParameter('status', 'OK')
        ->getQuery();

        return $q->getResult();
    }
    
}
