<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{

    public function Alerts() {
        
        $q = $this
        ->createQueryBuilder('e')
        ->where('e.active = :active')
        ->OrderBy('e.pattern,e.status,e.exit_codes')
        ->setParameter('active', 1)
        ->getQuery();

        return $q->getResult();
    }

    
}
