<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronRepository extends EntityRepository
{

    public function findTaskToExecute($date) {
        
        $q = $this
        ->createQueryBuilder('e')
        ->where('e.active > 0')        
//        ->orWhere('e.next_run is null')
        ->andWhere('e.next_run <= :date')                
        ->OrderBy('e.next_run')
        ->setParameter('date', $date)
        ->getQuery();

        return $q->getResult();
    }

}
