<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorLogRepository extends EntityRepository
{
    
   public function findErrors()
   {
        return $this->createQueryBuilder('e')
              ->Select('e.logtime,e.module,e.username,e.message,e.ip,e.trace,e.code,e.file_name')
              ->orderBy('e.logtime','DESC')
              ->getQuery()
              ->getResult();
   }
    
}
