<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
    
   public function findSpoolers()
   {
        return $this->createQueryBuilder('node')
              ->Select('node.name,node.description,node.type,conn.protocol,conn.host,conn.port,conn.login,conn.password,conn.key,conn.auth_method')
              ->LeftJoin('AriiCoreBundle:NodeConnection','nc',
                    \Doctrine\ORM\Query\Expr\Join::WITH,
                    'node = nc.node')
              ->LeftJoin('AriiCoreBundle:Connection','conn',
                    \Doctrine\ORM\Query\Expr\Join::WITH,
                    'nc.connection = conn')
              ->Where('node.role = :role')
              ->setParameter('role','jobscheduler')
              ->getQuery()
              ->getResult();
   }
    
}
