<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository
{
    
   public function findParams($bundle='Core')
   {
        return $this->createQueryBuilder('parameter')
              ->Select('parameter.id,parameter.name,parameter.value,parameter.type')
              ->orderBy('parameter.name')
              ->Where('parameter.bundle = :bundle')
              ->andWhere('parameter.domain != :domain')
              ->setParameter('bundle',$bundle)
              ->setParameter('domain','color')
              ->getQuery()
              ->getResult();
   }
   
   public function findBundles()
   {
        return $this->createQueryBuilder('parameter')
              ->Select('distinct parameter.bundle')
              ->orderBy('parameter.bundle')
              ->getQuery()
              ->getResult();
   }
    
}
