<?php

namespace Arii\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
   public function findDomains()
   {
        return $this->createQueryBuilder('dom')
            ->Select('dom.name,dom.title')
            ->orderBy('dom.title,dom.name')
            ->getQuery()
            ->getResult();
   }
  
}