<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * APPDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APPDayRepository extends EntityRepository
{
  
}