<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BKP_REFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BKP_REFRepository extends EntityRepository
{
   public function findLast()
   {
        return $this->createQueryBuilder('bkp')
            ->Select('count(bkp) as NB,max(bkp.updated) as lastUpdate')
            ->getQuery()
            ->getResult();
   }    
}
