<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CALRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CALRepository extends EntityRepository
{
    
   public function findNextStarts(\DateTime $date )
   {
        return $this->createQueryBuilder('cal')
            ->Select('cal.name,min(cal.day) as next')
            ->where('cal.day >= :date')
            ->groupBy('cal.name')
            ->orderBy('next')
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();
   }
    
}
