<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JOBMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JOBMonthRepository extends EntityRepository
{

   public function findJobsByMonth($start, $end, $env='P', $app='*')
   {
       if ($app=='*') {
            return $this->createQueryBuilder('job')
                 ->Select('job.year,job.month,sum(job.jobs) as jobs,sum(job.created) as created,sum(job.deleted) as deleted')
                 ->where('job.year*100+job.month >= :start')
                 ->andWhere('job.year*100+job.month <= :end')
                 ->andWhere('job.env = :env')
                 ->groupBy('job.year,job.month')
                 ->orderBy('job.year,job.month')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->getQuery()
                 ->getResult();
       }
       else {
            return $this->createQueryBuilder('job')
                 ->Select('job.year,job.month,job.application,job.jobs,job.created,job.deleted')
                 ->where('job.year*100+job.month >= :start')
                 ->andWhere('job.year*100+job.month <= :end')
                 ->andWhere('job.env = :env')
                 ->andWhere('job.application = :app')
                 ->orderBy('job.year,job.month')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->setParameter('app', $app)
                 ->getQuery()
                 ->getResult();
       }
   }

   // 19.05.2017: suppression des applications inactives
   public function findApplications($year,$month,$env='*')
   {
       if (($env=='*') or ($env=='')) {
            return $this->createQueryBuilder('job')
                ->Select('job.application','job.jobs')
                ->where('job.year = :year')
                ->andWhere('job.month = :month')
                ->orderBy('job.jobs','DESC')
                ->setParameter('year', $year)
                ->setParameter('month', $month)
                ->getQuery()
                ->getResult();
       }
       else {
            return $this->createQueryBuilder('job')
                ->Select('job.application','job.jobs')
                ->where('job.year = :year')
                ->andWhere('job.month = :month')                        
                ->andWhere('job.env = :env')
                ->orderBy('job.jobs','DESC')
                ->setParameter('year', $year)
                ->setParameter('month', $month)
                ->setParameter('env', $env)
                ->getQuery()
                ->getResult();
       }
   }   
   
   public function findApplicationsByMonths($start,$end, $env='P')
   {
        if ($env=='*') {
            $qb = $this->createQueryBuilder('job')
                ->Select('job.year,job.month,job.application,job.jobs,job.created,job.deleted')
                 ->where('(job.year*100+job.month) >= :start')
                 ->andWhere('(job.year*100+job.month) <= :end')
                ->orderBy('job.year,job.month,job.application,job.jobs','DESC')
                ->setParameter('start', $start)
                ->setParameter('end', $end);
                /*
                        $query = $qb->getQuery();
                        print $query->getSQL();
                        print_r($query->getParameters());
                        exit();
                */
        }
        else {
            $qb = $this->createQueryBuilder('job')
                ->Select('job.year,job.month,job.application,job.jobs,job.created,job.deleted')
                 ->where('(job.year*100+job.month) >= :start')
                 ->andWhere('(job.year*100+job.month) <= :end')
                ->andWhere('job.env = :env')                        
                ->orderBy('job.year,job.month,job.application,job.jobs','DESC')
                ->setParameter('start', $start)
                ->setParameter('end', $end)            
                ->setParameter('env', $env);
        }
        return $qb->getQuery()
                ->getResult();
   }
   
}