<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RUNDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RUNDayRepository extends EntityRepository
{
   public function findRunsMonth()
   {
        $driver = $this->_em->getConnection()->getDriver()->getName();
        switch ($driver) {
            case 'oci8':
                $sql = "SELECT EXTRACT(YEAR FROM run.run_date) as run_year,EXTRACT(MONTH FROM run.run_date) as run_month,run.application,run.env,run.spooler_type,run.spooler_name,sum(run.executions) as runs,sum(run.alarms) as alarms,sum(run.acks) as acks
                        FROM REPORT_RUN_DAY run
                        GROUP BY EXTRACT(YEAR FROM run.run_date),EXTRACT(MONTH FROM run.run_date),run.application,run.env,run.spooler_type,run.spooler_name";

                $rsm = new ResultSetMapping();
                $rsm->addScalarResult('RUN_YEAR', 'run_year');
                $rsm->addScalarResult('RUN_MONTH', 'run_month');                
                $rsm->addScalarResult('APPLICATION', 'application');
                $rsm->addScalarResult('ENV', 'env');
                $rsm->addScalarResult('SPOOLER_TYPE', 'spooler_type');
                $rsm->addScalarResult('SPOOLER_NAME', 'spooler_name');
                $rsm->addScalarResult('RUNS', 'runs');
                $rsm->addScalarResult('ALARMS', 'alarms');
                $rsm->addScalarResult('ACKS', 'acks');
                $query = $this->_em->createNativeQuery($sql, $rsm);
                return $query->getResult();         
                break;
            default:
                return $this->createQueryBuilder('run')
                      ->Select('Year(run.date) as run_year,Month(run.date) as run_month,run.application,run.env,run.spooler_type,run.spooler_name,sum(run.executions) as runs,sum(run.alarms) as alarms,sum(run.acks) as acks')
                      ->groupBy('run_year,run_month,run.application,run.env,run.spooler_type,run.spooler_name')
                      ->getQuery()
                      ->getResult();
                break;
        }
   }

   public function findRunsDay($start,$end,$env='*') {
       if (($env=='*') or ($env=='')) {
            return $this->createQueryBuilder('run')
                ->Select('run.date,run.application,run.env,run.spooler_type,run.spooler_name,sum(run.executions) as executions,sum(run.alarms) as alarms,sum(run.acks) as acks')
                ->where('run.date >= :start')
                ->andWhere('run.date <= :end')
                ->groupBy('run.date,run.env,run.spooler_type,run.spooler_name')
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->getQuery()
                ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                ->Select('run.date,run.application,run.env,run.spooler_type,run.spooler_name,run.executions,run.alarms,run.acks')
                ->where('run.date >= :start')
                ->andWhere('run.date <= :end')
                ->andWhere('run.env = :env')
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->setParameter('env', $env)
                ->getQuery()
                ->getResult();
       }
}
   
   public function findByDay()
   {
        return $this->createQueryBuilder('run')
              ->Select('run.date,run.env,run.spooler_type,run.spooler_name,sum(run.alarms) as runs')
              ->groupBy('run.date,run.env,run.spooler_type,run.spooler_name')
              ->getQuery()
              ->getResult();
   }

   /* liste d'applications concernée par les excutions */
   public function findApplications($start,$end,$env='*')
   {
       if (($env=='*') or ($env=='')) {
            return $this->createQueryBuilder('run')
                ->Select('run.application','app.title','sum(run.alarms) as nb')
                ->leftJoin('Arii\CoreBundle\Entity\Application','app',\Doctrine\ORM\Query\Expr\Join::WITH,'run.application = app.name')                
                ->where('run.date >= :start')
                ->andWhere('run.date <= :end')
                ->groupBy('run.application,app.title')
                ->orderBy('nb','DESC')
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->getQuery()
                ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                ->Select('run.application','app.title','sum(run.alarms) as nb')
                ->leftJoin('Arii\CoreBundle\Entity\Application','app',\Doctrine\ORM\Query\Expr\Join::WITH,'run.application = app.name')                
                ->where('run.date >= :start')
                ->andWhere('run.date <= :end')
                ->andWhere('run.env = :env')
                ->groupBy('run.application,app.title')
                ->orderBy('nb','DESC')
                ->setParameter('start', $start)
                ->setParameter('end', $end)
                ->setParameter('env', $env)
                ->getQuery()
                ->getResult();
       }
   }

   public function findAlarms($time, $app='%', $env='P')
   {
       if (($env=='*') or ($env=='')) {
            return $this->createQueryBuilder('run')
                ->Select('run.application','sum(run.alarms) as nb')
                ->where('run.date > :time')
                ->groupBy('run.application')
                ->orderBy('nb','DESC')
                ->setParameter('time', $time)
                ->getQuery()
                ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                ->Select('run.application','run.env','sum(run.alarms) as nb')
                ->where('run.date > :time')
                ->andWhere('run.env = :env')
                ->groupBy('run.application','run.env')
                ->orderBy('nb','DESC')
                ->setParameter('time', $time)
                ->setParameter('env', $env)
                ->getQuery()
                ->getResult();
       }
   }

   public function findAcks($time, $app='%', $env='P')
   {
        return $this->createQueryBuilder('run')
            ->Select('run.application','run.env','sum(run.acks) as nb')
            ->where('run.date > :time')
            ->andWhere('run.env = :env')
            ->groupBy('run.application','run.env')
            ->orderBy('nb','DESC')
            ->setParameter('time', $time)
            ->setParameter('env', $env)
            ->getQuery()
            ->getResult();
   }
   
   public function findExecutions($start,$end, $env='P', $app='ALL')
   {
       if (($app=='*') and ($env=='*')) {
           return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->groupBy('annee,mois')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->getQuery()
                 ->getResult();
       }
       elseif ($app=='*') {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,run.env,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.env = :env')
                 ->groupBy('annee,mois,run.env')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->getQuery()
                 ->getResult();
       }
       elseif ($env=='*') {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,run.application,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.application = :app')
                 ->groupBy('annee,mois,run.application')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('app', $app)
                 ->getQuery()
                 ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.env = :env')
                 ->andWhere('run.application = :app')
                 ->groupBy('annee,mois')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->setParameter('app', $app)
                 ->getQuery()
                 ->getResult();
       }
   }

   public function findExecutionsByMonth($start,$end, $env='P', $app='*')
   {
       if (($app=='*') and ($env=='*')) {
           return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->groupBy('annee,mois')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->getQuery()
                 ->getResult();
       }
       elseif ($app=='*') {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,run.env,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.env = :env')
                 ->groupBy('annee,mois,run.env')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->getQuery()
                 ->getResult();
       }
       elseif ($env=='*') {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,run.application,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.application = :app')
                 ->groupBy('annee,mois,run.application')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('app', $app)
                 ->getQuery()
                 ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                 ->Select('Year(run.date) as annee,Month(run.date) as mois,sum(run.warnings) as warnings,sum(run.alarms) as alarms,sum(run.acks) as acks,sum(run.executions) as executions')
                 ->where('run.date >= :start')
                 ->andWhere('run.date <= :end')
                 ->andWhere('run.env = :env')
                 ->andWhere('run.application = :app')
                 ->groupBy('annee,mois')
                 ->setParameter('start', $start)
                 ->setParameter('end', $end)
                 ->setParameter('env', $env)
                 ->setParameter('app', $app)
                 ->getQuery()
                 ->getResult();
       }
   }
   
   public function findExecutionsByApp(\DateTime $time, $app='%', $env='')
   {
       if (($env=='*') or ($env=='')) {
           return $this->createQueryBuilder('run')
                ->Select('Month(run.date) as mois,run.env,run.alarm,run.ack,count(run) as nb')
                ->where('run.date > :time')
                ->andWhere('run.application = :app')
                ->groupBy('mois,run.env,run.alarm,run.ack')
                ->setParameter('time', $time)
                ->setParameter('app', $app)
                ->getQuery()
                ->getResult();
       }
       else {
            return $this->createQueryBuilder('run')
                ->Select('Month(run.date) as mois,run.env,run.alarm,run.ack,count(run) as nb')
                ->where('run.date > :time')
                ->andWhere('run.env = :env')
                ->andWhere('run.application = :app')
                ->groupBy('mois,run.env,run.alarm,run.ack')
                ->setParameter('time', $time)
                ->setParameter('app', $app)
                ->setParameter('env', $env)
                ->getQuery()
                ->getResult();
           
       }
   }
   
   public function findLast()
   {
        return $this->createQueryBuilder('run')
            ->Select('count(run) as NB,max(run.date) as lastUpdate')
            ->getQuery()
            ->getResult();
   }
   
}