<?php

namespace Arii\TimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaysRepository extends EntityRepository
{
}
