<?php

namespace Arii\TimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulesRepository extends EntityRepository
{
    
   public function findRules()
   {
       return $this->createQueryBuilder('tz')
            ->Select('tz.id','tz.rule','tz.name','tz.title','tz.description')
            ->orderBy('tz.name','ASC')
            ->getQuery()
            ->getResult();
   }

   public function findRule($id)
   {
       return $this->createQueryBuilder('tz')
            ->Select('tz.id','tz.rule','tz.name','tz.title','tz.description','(tz.zone) as zone_id')
            ->Where('tz.id = :id')
            ->orderBy('tz.name','ASC')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
   }
   
}
