<?php

namespace Arii\TimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonesRepository extends EntityRepository
{
    
   public function findZones()
   {
       return $this->createQueryBuilder('tz')
            ->Select('tz.id,tz.name,tz.title,tz.description,(tz.country) as country_id,tz.latitude,tz.longitude')
            ->orderBy('tz.name','ASC')
            ->getQuery()
            ->getResult();
   }

   public function findZone($id)
   {
       return $this->createQueryBuilder('tz')
            ->Select('tz.id','tz.name','tz.title')
            ->Where('tz.id = :id')
            ->orderBy('tz.name','ASC')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
   }
   
}
