<?php

namespace Arii\JOCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * state_job_chain_nodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobChainNodesRepository extends EntityRepository
{
}
