<?php

namespace Arii\JOCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * statelocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocksRepository extends EntityRepository
{
}
