<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoJobstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoJobstRepository extends EntityRepository
{
    // Pour la synchronisation des acquittements
    public function synchroJobst($past) {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.jobName,e.description,e.jobType,e.runNum,e.ntry,e.lastStart,e.lastEnd,e.exitCode,e.runMachine,e.status')
        ->where('e.statusTime > :past')
        ->setParameter('past', $past)
        ->getQuery();
        return $q->getResult();
    }
    
}
