<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerOrderHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerOrderHistoryRepository extends EntityRepository
{
    // Pour la synchronisation des acquittements
    // 4 jours en arriere
    public function synchroOrderHistory() {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.jobName,e.description,e.jobType,e.runNum,e.ntry,e.lastStart,e.lastEnd,e.exitCode,e.runMachine,e.status')
        ->getQuery();
        return $q->getResult();
    }
    
}
