<?php

namespace Arii\SelfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('created' => 'DESC'));
    }
    
    public function findRequests()
    {
        $query = $this->createQueryBuilder('job')
            ->Select('job.*')
            ->orderBy('job.title');        
            return $query->getQuery()
                    ->getResult();
    }

    public function findTodo($model)
    {
        $query = $this->createQueryBuilder('req')
            ->Select('req.run_command','req.parameters','req.created')
            ->Where('req.name = :model')
            ->andWhere('req.processed is NULL')
            ->orderBy('req.created')
            ->setParameter('model',$model);
        return $query->getQuery()
                    ->getResult();
    }   
        
    public function findProcessed($name)
    {
        $query = $this->createQueryBuilder('job')
            ->Select('job')
            ->where('job.name = :name')
            ->andWhere('job.processed IS NOT NULL')
            ->andWhere('job.run_exit = 0')
            ->setParameter('name',$name);
            return $query->getQuery()
                    ->getResult();
    }
    
}
